# Generated by Django 6.0.5 on 2026-06-22 02:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('PRODUCTEUR', 'Producteur'), ('COMMERCANT', 'Commerçant'), ('TRANSPORTEUR', 'Transporteur'), ('ADMIN', 'Administrateur')], max_length=20)),
                ('localisation', models.CharField(blank=True, default='Non précisée', max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_mission', models.CharField(default='EN_ATTENTE', max_length=20)),
                ('date_assignation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=150)),
                ('categorie', models.CharField(max_length=80)),
                ('quantite_dispo', models.IntegerField(default=0)),
                ('unite_mesure', models.CharField(default='kg', max_length=20)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image_produit', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('zone_production', models.CharField(blank=True, max_length=150, null=True)),
                ('date_disponibilite', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id_statistique', models.AutoField(primary_key=True, serialize=False)),
                ('total_missions', models.IntegerField(default=0)),
                ('total_litiges', models.IntegerField(default=0)),
                ('chiffre_affaires_global', models.FloatField(default=0.0)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='administrateur', serialize=False, to='gestion_agro.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Commercant',
            fields=[
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='commercant', serialize=False, to='gestion_agro.utilisateur')),
                ('entreprise', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse_boutique', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='producteur', serialize=False, to='gestion_agro.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='transporteur', serialize=False, to='gestion_agro.utilisateur')),
                ('type_vehicule', models.CharField(blank=True, max_length=80, null=True)),
                ('capacite_transport_int', models.IntegerField(default=0)),
                ('disponibilite', models.BooleanField(default=True)),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart_prevue', models.DateTimeField(blank=True, null=True)),
                ('date_arrivee_prevue', models.DateTimeField(blank=True, null=True)),
                ('etat_livraison', models.CharField(default='EN_ATTENTE', max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='gestion_agro.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Litige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('statut_litige', models.CharField(default='OUVERT', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges', to='gestion_agro.mission')),
            ],
        ),
        migrations.CreateModel(
            name='FluxProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_depart', models.CharField(max_length=150)),
                ('zone_arrivee', models.CharField(max_length=150)),
                ('quantite', models.IntegerField()),
                ('date_flux', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flux', to='gestion_agro.produits')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('statut_reservation', models.CharField(default='EN_ATTENTE', max_length=20)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('nom_chauffeur', models.CharField(blank=True, max_length=150, null=True)),
                ('telephone_chauffeur', models.CharField(blank=True, max_length=30, null=True)),
                ('type_vehicule', models.CharField(blank=True, max_length=80, null=True)),
                ('prix_transport_propose', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('flux_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gestion_agro.fluxproduit')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gestion_agro.commercant')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paiement', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=120, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='EN_ATTENTE', max_length=20)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion_agro.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='gestion_agro.reservation'),
        ),
        migrations.AddField(
            model_name='produits',
            name='producteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='gestion_agro.producteur'),
        ),
        migrations.AddField(
            model_name='mission',
            name='transporteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='gestion_agro.transporteur'),
        ),
        migrations.CreateModel(
            name='Caution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_caution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('etat_caution', models.CharField(default='ACTIVE', max_length=20)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cautions', to='gestion_agro.reservation')),
                ('transporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cautions', to='gestion_agro.transporteur')),
            ],
        ),
    ]
