# Generated by Django 6.0.5 on 2026-06-23 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='flux_produit',
            new_name='fluxproduit',
        ),
        migrations.AddField(
            model_name='reservation',
            name='transporteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='gestion_agro.transporteur'),
        ),
        migrations.AlterField(
            model_name='fluxproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.produits'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='profil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_producteur', serialize=False, to='gestion_agro.utilisateur'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut_reservation',
            field=models.CharField(default='EN_ATTENTE', max_length=30),
        ),
    ]
