# Generated by Django 6.0.5 on 2026-06-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0002_rename_flux_produit_reservation_fluxproduit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut_reservation',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE', 'Payée'), ('VALIDEE', 'Validée'), ('PROPOSITION_TRANSPORT', 'Proposition transport'), ('ACCEPTEE', 'Acceptée'), ('CHARGEE', 'Chargée'), ('EN_TRANSIT', 'En transit'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type_vehicule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
